### ISSUE TITLE
Updated from 2024.15 to 2024.55, caused Design template to stop working

### ISSUE THREAD

**Issue by WafflesExploits** [Syslifters/sysreptor#283]
Hi, my design stopped working after updating to 2024.55. It worked without a problem before, but now I got the following errors:
```
ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

27 |  
28 |  <table-of-contents id="toc" v-slot="tocItems">
29 |      <h1>Table of Contents</h1>
   |      ^^^^^^^^
30 |      <br>
31 |      <ul>

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

58 |  
59 |  
60 |  <div v-if="report.pentesters_list[0] || report.clients_list[0]">
   |                                       ^^^^^^^
61 |      <h1 id="contact-information" class="in-toc">Contact Information</h1>
62 |      <markdown>

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

74 |              <tr v-for="client_item in report.clients_list">
75 |                  <td class="table-technical">{{ client_item.name }}</td>
76 |                  <td class="table-technical">{{ client_item.title }}</td>
   |                ^^^^^^^^
77 |                  <td class="table-technical">{{ client_item.info }}</td>
78 |              </tr>

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

13 |  <section id="page-cover" data-sysreptor-generated="page-cover">
14 |      <div class="page-cover-title">
15 |          {{report.client_company.name}}
   |          ^^^^^^^^^^^^
16 |      </div>
17 |  

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

6  |  
7  |  <div data-sysreptor-generated="page-footer" id="footer">
8  |      <div id="footer-left"><em>Business Confidential</em></div>
   |                                     ^^^^^^^^^^^^
9  |      <div id="footer-center">{{ report.client_company.name }}</div>
10 |  </div>

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

69 |              <tr v-if="report.clients_list[0]" style="background-color: #BBD4EC;">
70 |                  <td><strong>{{ report.client_company.name }}</strong></td>
71 |                  <td></td>
   |                   ^^^^^^^^
72 |                  <td></td>
73 |              </tr>

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

35 |                      <ref :to="item.id" />
36 |                  </div>
37 |                  <div v-else><ref :to="item.id" /></div>
   |                                              ^^^^^^^^^^
38 |              </li>
39 |          </div>

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

20 |          
21 |          <span v-if="report.project_name" class="page-cover-address">Project: {{ report.project_name }}<br></span>
22 |          <span v-if="report.report_version" class="page-cover-address">Version: {{ report.report_version }}</span>
   |                  ^^^^^^^^
23 |          </p>
24 |      </div>

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

62 |      <markdown>
63 |          <table class="table-technical">
64 |              <tr style="border-bottom: none;">
   |                                          ^^^^^
65 |                  <th>Name</td>
   |  ^
66 |                  <th>Title</td>

ERROR

Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"

45 |      <h1 id="confidentiality-statement" class="in-toc">Confidentiality Statement</h1>
46 |      <markdown>
47 |  <markdown v-if="report.confidentiality_statement" :text="report.confidentiality_statement" />
   |      ^^^^^^^^^^
48 |  </markdown>
49 |  </div>

ERROR

TypeError: Cannot read properties of null (reading 'querySelectorAll') in design "PNPT Exam"

Error in mounted hook

ERROR

Uncaught error during template rendering in design "PNPT Exam"

Failed to execute 'setAttribute' on 'Element': '&#x22;' is not a valid attribute name.

WARNING

Invalid reference in design "PNPT Exam"

Referenced element with id="Technical-Findings-section" not found.
```

**Comment by MWedl** [comment]
Hi, could you provide us your design that we can take a look at it. We could not reproduce the problem from the error messages. There are many `Template compilation error: v-slot can only be used on components or <template> tags. in design "PNPT Exam"` messages with no `v-slot` in the code snippet.

**Comment by WafflesExploits** [comment]
[design.tar.gz](https://github.com/user-attachments/files/16106437/design.tar.gz)

**Comment by WafflesExploits** [comment]
The design is the file I just uploaded

**Comment by MWedl** [comment]
You design contains invalid HTML. It should not have worked in previous versions. We recommend to update your design's HTML.

For example you used `<th>` as starting tag and `<td>` as end tag multiple times.
```html
<div>
    <h1 id="finding-severity-ratings" class="in-toc">Finding Severity Ratings</h1>
    <markdown>
        {{ report.severitys_all.summary }}
        <table class="table-technical">
            <tr>
                <th style="width:20%">Severity</td>
                <th style="width:20%">CVSS V3 Score Range</td>
                <th style="width:80%">Definition</td>
            </tr>
...
```

Normally, invalid HTML would produce meaningful error messages, but in you design the invalid HTML was inside `<markdown>` tags. For `<markdown>` tags we currently cannot produce detailed error messages.

Because of that, we recommend to remove any unneeded `<markdown>` wrappers, i.e. when you only use HTML and Vue template language inside `<markdown>` tags and not actual markdown syntax. In your design you can remove all `<markdown>` wrappers that do not have the `:text="..."` attribute set, because you never use markdown syntax.

**Comment by WafflesExploits** [comment]
I fixed the HTML issues, and removed all markdown tags, except the ones with `:text="..."`, and it worked! Thanks!
